### ISSUE TITLE
Coding styles

### ISSUE THREAD

**Issue by johanmon** [ID1019/functional-programming#16]
Some coding styles i.e. naming of functions, variables, files etc. Haven't gone through them all but if we don't have any other guide line this could be it.

https://github.com/christopheradams/elixir_style_guide

**Comment by SimoneStefani** [comment]
Totally agree, I have tried to use that guide as coding style guidelines.
I´m planning to write a `CONTRIBUTING.md` file which mentions that guide and also lists the most common style features (naming, functions, modules).

I will try to do it tomorrow.

It would be great to go through all the files and check for consistency.

Two subtle issues are:
- blank spaces, EOL chars, etc (there should always be a blank line at EOF)
- use `defp` for private functions

**Comment by johanmon** [comment]
Great, 

the use of defp is of course encouraged but I removed it from the initial tutorial since I thought that exporting everything makes it easier to test all function in a module.
