### ISSUE TITLE
Usage of Structs

### ISSUE THREAD

**Issue by johanmon** [ID1019/functional-programming#27]
I'm going through the slides for the tracer (which will be so much better using Structs instead of Records). I was looking at the code for the tracer and saw some things that we might do different:

In the definition of Sphere we have a functions that constructs a sphere but this can now be removed and instead let the user of the module construct an object using the Sphere Structs. Why I had the functions in Erlang was because I didn't want to export the record structure but needed a way of doing key-value description. Any thoughts?

The second thing was using the struct() function to construct a new object but why not use the %Struct{} syntax?

**Comment by SimoneStefani** [comment]
Totally agree with both. I used those because at the beginning I didn't know what was the best approach. Should I change them or are you going to do that @johanmon?

**Comment by johanmon** [comment]
Are, we should enforce checken The Strut.

I'll fix

**Comment by SimoneStefani** [comment]
Nice. If you want to compile all the files in a folder (e.g. tracer) you can open iex in that folder and run `c(Path.wildcard("./*.ex"))`

**Comment by johanmon** [comment]
I've rewritten the tracer and used the struct feature to simplify things. I've also removed a lot of code form the slides since the seminar should be more interactive. Also removed the refraction since it dod not actually work in all general cases. It's better if students experiment with this instead at looking at code that only solved it half-way.
