### ISSUE TITLE
Dead Links: Exercise Description

### ISSUE THREAD

**Issue by Daynex** [ID1019/functional-programming#56]
All description links at [functional-programming/exercises/](https://github.com/ID1019/functional-programming/tree/master/exercises) are not working.

**Comment by johanmon** [comment]
Which lika?

**Comment by johanmon** [comment]
Which links?

**Comment by Daynex** [comment]
In the  README.md 
Sorry for not being specific in my Issue.

**Comment by GaPhil** [comment]
@johanmon I think @Daynex means these: https://github.com/ID1019/functional-programming/blob/master/exercises/README.md

**Comment by johanmon** [comment]
Thanks - added template readme files.
